### ISSUE TITLE
Более подробный readme

### ISSUE THREAD

**Issue by kazqvaizer** [fandsdev/sentry2basecamp#3]
@nvo87 можешь пожалуйста расписать подробнее в readme, для чего нужно форвардить вебхуки? Я задумался над системой оповещения для basecamp, и хочу узнать что это, для чего это и как можно использовать.

**Comment by nvo87** [comment]
@kazqvaizer ок, запишу! сорри, я потерял это уведомление (

**Comment by nvo87** [comment]
готово
